[program:libraryapp-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/librarysystem/artisan queue:work --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/librarysystem/storage/logs/worker.log
stopwaitsecs=3600

[program:libraryapp-scheduler]
process_name=%(program_name)s
command=php /var/www/librarysystem/artisan schedule:run --no-interaction
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/librarysystem/storage/logs/scheduler.log